let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "ማሽላ",
    price: 45,
    desc: "በፕሮቲን እና ፋይበር የበለፀገ",
    img: "images/mashela.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "ሽንብራ",
    price: 60,
    desc: "የአመጋገብ ፋይበር፣ ቫይታሚን ሲ፣ ፖታሲየም",
    img: "images/shenebera.jpg",
  },
  {
    id: "qwertyuimnbvcx",
    name: "ባቄላ",
    price: 60,
    desc: "ፕሮቲን፣ ፋይበር፣ የቪታሚኖች እና ማዕድናት ምንጭ",
    img: "images/bakela.jpg",
  },
  {
    id: "fgvbcewasdfgh",
    name: "ስንዴ",
    price: 60,
    desc: "የካርቦሃይድሬትስ፣ ፋይበር እና ፕሮቲን ምንጭ ነው",
    img: "images/sendea.jpg",
  },
  {
    id: "samueltekie",
    name: "ቀይ ስንዴ",
    price: 60,
    desc: "የካርቦሃይድሬትስ፣ ፋይበር እና ፕሮቲን ምንጭ ነው",
    img: "images/keysende.jpg",
  },
  {
    id: "firamosafikdadu",
    name: "በቆሎ",
    price: 40,
    desc: "እንደ ቫይታሚን B6፣ ታይሚን እና ፖታሺየም ያሉ የካርቦሃይድሬትስ፣ ፋይበር እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ",
    img: "images/bekello.jpg",
  },
  {
    id: "mekidesmarie",
    name: "አጃ",
    price: 90,
    desc: "እንደ ቲያሚን፣ ማግኒዥየም እና ፎስፎረስ ያሉ እጅግ በጣም ጥሩ የአመጋገብ ፋይበር",
    img: "images/aja.jpg",
  },
  {
    id: "abaynehabay",
    name: "ሽንብራ ሽሮ",
    price: 85,
    desc: "ጥሩ የአመጋገብ ፋይበር፣ ቫይታሚን ሲ፣ ፖታሲየም",
    img: "images/sheneberashero.jpg",
  },
  {
    id: "hermelakidane",
    name: "አተር ሽሮ",
    price: 85,
    desc: "ጥሩ የአመጋገብ ፋይበር፣ ቫይታሚን ሲ፣ ፖታሲየም",
    img: "images/atershero.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "ምስር",
    price: 165,
    desc: "የእፅዋት ፕሮቲን፣ ፋይበር፣ ብረት እና ፎሌት ምንጭ ናቸው",
    img: "images/misir.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "ሩዝ",
    price: 80,
    desc: "እንደ ቲያሚን፣ ኒያሲን እና ብረት ያሉ የካርቦሃይድሬትስ፣ ፋይበር እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ ነው",
    img: "images/ruz.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "ገብስ",
    price: 55,
    desc: "እንደ ብረት፣ ማግኒዚየም እና ሴሊኒየም ያሉ እጅግ በጣም ጥሩ የፋይበር፣ ፕሮቲን እና አስፈላጊ የቪታሚኖች",
    img: "images/gebes.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "አተር",
    price: 110,
    desc: "በፋይበር፣ ፕሮቲን፣ እና እንደ ቫይታሚን ሲ፣ ቫይታሚን ኬ እና ፎሌት ባሉ አስፈላጊ ቪታሚኖች እና ማዕድናት የበለፀገ",
    img: "images/aterkik.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "በቸና ጤፍ",
    price: 85,
    desc: "እንደ ብረት፣ ካልሲየም እና ቫይታሚን ሲ ያሉ የፋይበር፣ ፕሮቲን እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ ነው።",
    img: "images/bechoteff.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "የደብረ ብርሀን ጤፍ",
    price: 75,
    desc: "እንደ ብረት፣ ካልሲየም እና ቫይታሚን ሲ ያሉ የፋይበር፣ ፕሮቲን እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ ነው።",
    img: "images/debrebrihanteff.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "የጎጃም ጤፍ",
    price: 84,
    desc: "እንደ ብረት፣ ካልሲየም እና ቫይታሚን ሲ ያሉ የፋይበር፣ ፕሮቲን እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ ነው።",
    img: "images/yegojjamteff.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "የደብረ ብርሀን ጤፍ ደረጃ1",
    price: 95,
    desc: "እንደ ብረት፣ ካልሲየም እና ቫይታሚን ሲ ያሉ የፋይበር፣ ፕሮቲን እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ ነው።",
    img: "images/yedbteff.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "የጎጃም ጤፍ ደረጃ 1",
    price: 85,
    desc: "እንደ ብረት፣ ካልሲየም እና ቫይታሚን ሲ ያሉ የፋይበር፣ ፕሮቲን እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ ነው።",
    img: "images/yegojjamteff2.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "በቸና ጤፍ ደረጃ 2",
    price: 350,
    desc: "እንደ ብረት፣ ካልሲየም እና ቫይታሚን ሲ ያሉ የፋይበር፣ ፕሮቲን እና አስፈላጊ የቪታሚኖች እና ማዕድናት ምንጭ ነው።",
    img: "images/bichena2teff.jpg",
  },
];
